### ISSUE TITLE
丢失BattleLogic文件

### ISSUE THREAD

**Issue by better666** [CraneInForest/LockStepSimpleFramework-Client#1]
BattleLogic缺失

**Comment by 6846541561** [comment]
同上，如何解决

**Comment by CraneInForest** [comment]
https://github.com/CraneInForest/LockStepSimpleFramework-Shared.git
共享逻辑以子模块的形式分别加入到客户端和服务器中,如要运行源码请在clone完毕主仓库后再更新一下子模块,否则没有共享逻辑是无法通过编译的
